global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8001']

  - job_name: 'worker1'
    static_configs:
      - targets: ['worker1:8002']

  - job_name: 'worker2'
    static_configs:
      - targets: ['worker2:8003']

  - job_name: 'worker3'
    static_configs:
      - targets: ['worker3:8004']